#Note: No volumes needed, It's a test project for Devsu
version: '3.9'
services:
  sonarqube:
    container_name: sonarqube
    image: sonarqube:9.9-community
    restart: always
    ports:
      - 9000:9000
    networks:
      localnetwork:
        aliases:
          - sonarqube_net
  jenkins:
    container_name: jenkins
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    restart: always
    env_file:
      - jenkins/creds/credentials.txt
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - ./jenkins/creds/credentials.txt:/credentials.txt
    networks:
      localnetwork:
        aliases:
          - jenkins_net
networks:
  localnetwork:
    driver: bridge
    ipam:
      driver: default

# Change admin Password
# https://sunilhari.medium.com/how-to-integrate-sonarqube-and-jenkins-721d5efd3cb6
# curl -u admin:admin -X POST "http://localhost:9000/api/users/change_password?login=admin&previousPassword=admin&password=devsu2024"
# curl -u admin:devsu2024 -X POST "http://localhost:9000/api/user_tokens/generate?login=admin&name=testToken"

#squ_176e8ec2579d2dbfac2c8ed83b7a1b29e39c39e4

# https://docs.sonarsource.com/sonarqube/latest/setup-and-upgrade/install-the-server/installing-sonarqube-from-docker/