#Note: No volumes needed, It's a test project for Devsu
version: '3.9'
services:
  sonarqube:
    image: sonarqube:9.9-community
    restart: always
    ports:
      - 9000:9000
    networks:
      sonarqube_network:
        aliases:
          - sonarqube_network
networks:
  sonarqube_network:
    driver: bridge
    ipam:
      driver: default

# Change admin Password
# https://sunilhari.medium.com/how-to-integrate-sonarqube-and-jenkins-721d5efd3cb6
# curl -u admin:admin -X POST "http://localhost:9000/api/users/change_password?login=admin&previousPassword=admin&password=devsu2024"
# curl -u admin:devsu2024 -X POST "http://localhost:9000/api/user_tokens/generate?login=admin&name=testToken"

