##############
##  Debian  ##
##############
- name: Install latest version of Apache - {{ debian_family }}
  apt: name=apache2 state=latest update_cache=yes
  when: ansible_distribution in debian_family

- name: Instalar dependencias para Docker - {{ debian_family }}
  apt:
    name: "{{ item }}"
    state: present
  when: ansible_distribution in debian_family
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: Añadir la clave GPG oficial de Docker
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
  when: ansible_distribution in debian_family

- name: Agregar el repositorio de Docker
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
    state: present
  when: ansible_distribution in debian_family

- name: Actualizar la lista de paquetes de apt
  apt:
    update_cache: yes
  when: ansible_distribution in debian_family

- name: Instalar la última versión de Docker
  apt:
    name: 
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
      - docker-buildx-plugin 
      - docker-compose-plugin
    state: present
  when: ansible_distribution in debian_family

- name: Agregar usuario al grupo docker
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  when: ansible_distribution in debian_family

##################################
##  CentOs, Oracle Linux, RHEL  ##
##################################