@Library('infrastructure-pipelines@dev')

import org.emic.devsu.*

/*
 * Mandatory stages: Checkout & Build
 * Mantatory Variables
 *  - Variable Name: projectType 
 *      - String
 *      - Posible values: springboot, nodejs or django
 * TESTING (Optional Stage): 
 *  - You decide if use test Variable. If you want test:
 *    - Variable Name: test
 *          - Array[Boolean, Boolean, Boolean] 
 *          - Each element:
 *              - [0] => Unit Tests
 *              - [1] => Acceptance Tests
 *              - [2] => Integration Tests
 * CODE ANALYSIS (Optional Stage): 
 *  - You decide if use codeAnalysis Variable. If you want test:
 *    - Variable Name: codeAnalysis
 *          - Boolean
 * 
*/
mainInfrastructure {
    cloudType = "gcp"
}
