@Library('infrastructure-pipelines@dev')

import org.emic.devsu.*

/*
 * Stages: Checkout | Init | Plan | Apply | Post
 * cloudType: Choose among "gcp", "azure", "aws"
 * project: (GCP) ProjectID when the resource will be create
 * resourceType: Choose among "instance", "gke", etc
*/
mainInfrastructure {
    cloudType = "gcp"
    project = "devsu-project"
    resourceType = "instance"
    instanceName = "newvm01"
}



